# Generated by Django 3.2.5 on 2021-07-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_rename_flight_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
