# Generated by Django 3.2.5 on 2021-07-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_auto_20210726_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
